---
version: '3.7'

services:
  kibana:
    image: kibana:6.5.4
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:6.5.4
    environment:
      discovery.type: single-node
  logstash:
    # enable to debug logstash using "docker logs"
    logging:
      driver: json-file
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    image: logstash:6.5.4
    ports:
      - 12201:12201/udp

configs:
  logstash.conf:
     file: ./logstash.conf

networks:
  default:
    driver: overlay
    attachable: true # set for debugging
